### PR TITLE
Update Emotiv utils to use Cortex 2.0 API

### PR DESCRIPTION
**Pull request by jdpigeon**
This deprecates https://github.com/makebrainwaves/BrainWaves/pull/94 and allows the app to connect to Emotiv's via the new version of the Cortex app provided by Emotiv.

This is almost good to go, but merging of this should await a new license from Emotiv. The current license we have is expired, which prevents me from testing the raw EEG features. However, there doesn't appear to be any reason that they would have changed given the updates were primarily around authorization and device connectivity.

### CODE REVIEW

**Comment by jdpigeon** [comment]
Can confirm this gives us EEG connectivity to Emotiv again.

A lot of double quotes got converted to double quotes in this PR. I think I ran prettier on it a couple times without hooking into the right config, unfortunately. I'll go through and fix it up soon.

**Comment by teonbrooks** [comment]
@jdpigeon, did our keys.js (the one we bundle in at package build) file change?

do you want to land #101 and rebase this on top of it? @Yury-Shevchenko mentioned that he will apply his current changes after these two pr land

**Comment by teonbrooks** [comment]
tested this locally and it works. thanks @jdpigeon!

**Comment by jdpigeon** [comment]
Keys.js did not change! Emy reactivated our existing license.

**Pull request merged**
