### PR TITLE
eeg trial callback inside lab.js tasks

### PR DESCRIPTION
**Pull request by Yury-Shevchenko**
Added a callback inside lab.js tasks that fires at the onset of each trial, but did not test it yet.

### CODE REVIEW

**Comment by teonbrooks** [comment]
hey, we landed the fix for the emotiv creating a record, etc. you would need to rebase your pr on master to get the changes.

a few things:
- [ ] i just tried running it but I don't see that the markers were added, could you look into that?
- [ ] how are we handling exiting from experiments both in the middle and at the end? for both, i am stuck at the end and can't navigate away from the last screen
- [ ] could you change the markers from strings to int. the analysis part relies on them being integers. could you annotate what those values are. perhaps for faces and houses it could be 1 and 9 to correspond to the keys they are passing.

**Comment by Yury-Shevchenko** [comment]
It seems like the problem with closing the experiment also happens with jsPsych experiment - _state$_ does not have _device_ in it, and therefore cannot check whether the type of device is Emotiv. I am wondering whether it's because of changes in API.


Uncaught TypeError: Cannot read property 'deviceType' of undefined
    at MapSubscriber.action$.ofType.pipe [as project] (experimentEpics.js:153)
    at MapSubscriber.module.exports../app/node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:35)
    at MapSubscriber.module.exports../app/node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
    at SafeSubscriber.__tryOrUnsub (Subscriber.js:202)
    at SafeSubscriber.next (Subscriber.js:140)
    at Subscriber._next (Subscriber.js:86)
    at Subscriber.next (Subscriber.js:63)
    at SafeSubscriber.module.exports../app/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:192)
    at SafeSubscriber.module.exports../app/node_modules/rxjs/_esm5/internal/Subscriber.js.SafeSubscriber.next (Subscriber.js:130)
    at FilterSubscriber.module.exports../app/node_modules/rxjs/_esm5/internal/operators/filter.js.FilterSubscriber._next (filter.js:38)

**Comment by Yury-Shevchenko** [comment]
Hello Teon, it seems like markers are also not recorded for jsPsych experiment as well.

**Comment by teonbrooks** [comment]
closing for #106

**Pull request closed without merging**
